site_name: Causal Inference Studies
site_url: https://emiliomaddalena.github.io/causal-inference-studies/
repo_url: https://github.com/emilioMaddalena/causal-inference-studies
repo_name: GitHub
docs_dir: material
nav:
  - ğŸ  Home: index.md
  - ğŸ° Introduction:
      - Why causality matters: why_causality_matters.md
      - When regression goes wrong: when_regression_goes_wrong.md
      - When regression goes wrong 2: when_regression_goes_wrong_2.md
      - Association vs causation: association_vs_causation.md
      - Confounders: confounders.md
      - Causal questions: causal_questions.md
  - ğŸ“š Core concepts:
      - Potential outcomes: potential_outcomes.md
      - Causal effects: causal_effects.md
      - DAGs: dags.md
      - DAGs 2: dags_2.md
      - Feature selection: feature_selection.md
      - Feature selection 2: feature_selection_2.md
  - ğŸ“ Advanced topics:
      - A/B testing: ab_testing.md
      - Simpson's paradox: simpsons_paradox.md
      - Shapley values: shapley_values.md
      - Shapley cont'd: shapley_contd.md
      - Identification: identification.md
  - ğŸ“‘ Resources: resources.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: light blue
    - scheme: slate
      primary: blue
      accent: light blue
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - fenced_code
  - pymdownx.superfences
  - footnotes
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/style.css
